### ISSUE TITLE
where are train.sh and test.sh?

### ISSUE THREAD

**Issue by gghhoosstt** [Nardien/NMG#1]
hello, I‘am gonna run the code ，but where are train.sh and test.sh files?
looking forward to your reply！Thank you！

**Comment by Nardien** [comment]
Thank you for pointing it out. I will upload shell scripts as soon as possible.
Thank you.

**Comment by gghhoosstt** [comment]
Thank you for your efficiency！

**Comment by Nardien** [comment]
I upload the shell script and fix some bugs including the transformers library.
