### ISSUE TITLE
where is context file or at least you can give the scirpt rithg?

### ISSUE THREAD

**Issue by xugy16** [Nardien/NMG#5]

**Comment by Nardien** [comment]
Hi. Thank you for your interest in our work.

I recently upload the code for generating a context file in `build_corpus.py`.

You can use it as follows:

`python build_corpus.py -t SQuAD.jsonl -o squad_train.txt`

Please ensure that you should use the jsonl files downloaded from the [mrqa repository](https://github.com/mrqa/MRQA-Shared-Task-2019) for question answering task.

**Comment by vaibhav0195** [comment]
Hi is there any code to generate context for the classification task ?
thanks and regards!
